# Configurations
title:            Home page
longtitle:        Home page
author:           devopslondon2021
email:            devopslondon2021@gmail.com
description: >
  📍 Based in London: The heart of innovation and a technological powerhouse.

  🔧 15+ Years of Experience: Skilled in DevOps, Cloud Solutions, and Data Analytics.

  💡 Blockchain Enthusiast: Always exploring the cutting edge of decentralized technology.

  🎨 Creatively Driven: Passionate about Designing, Photography, and Cooking—blending art with technology.

  🌍 Freelancer Ready: Flexible and open to work with global teams across any time zone.

  ⏱ Quick Learner with a Positive Attitude: I thrive on new challenges and am always eager to learn.

  🤝 Open to Opportunities: Looking to make a substantial impact through exciting freelance projects.

version:          1.0
gitbook_version:  3.2.3

url:              'https://devopslondon2021.github.io/'
baseurl:          '/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
